name: rpbot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  build_runner: ^2.4.11
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  nyxx: ^6.3.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
