final Map<String, int> debuffs = {
  'Exhaustion': 5,
  'Insomnia': 10,
  'Hunger': 3,
  'Starvation': 6,
  'Thirst': 3,
  'Dehydration': 6,
  'Slightly Ill': 2,
  'Moderately Ill': 5,
  'Very Ill': 8,
  'Severely Ill': 10,
  'Alcohol Addiction': 3,
  'Nicotine Addiction': 4,
  'Drug Addiction': 5,
  'Minor Withdrawal': 3,
  'Moderate Withdrawal': 5,
  'Severe Withdrawal': 7,
  'Slightly Injured': 2,
  'Moderately Injured': 5,
  'Very Injured': 8,
  'Severely Injured': 10,
  'Panic': 5,
  'Moderate Pain': 4,
  'Severe Pain': 6,
  'Agony': 10,
  'Dirty': 0,
};

final Map<String, int> buffs = {
  'Caffeinated': 3,
  'Well Fed': 3,
  'Well Hydrated': 3,
  'Well Rested': 3,
  'Slightly Protected': 2,
  'Moderately Protected': 5,
  'Very Protected': 8,
  'Extremely Protected': 10,
};
